### PR TITLE
fix: convert css style

### LINKED ISSUE #202: Add Reporting module as supporting module in the Readme
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Module Version

2.0.0.1010

### Motivation

Hi i just saw your [blog post](https://blogs.vmware.com/cloud-foundation/2023/01/31/vmware-validated-solutions-jan-2023-update/) from vmware-validated-solutions-jan-2023-update,
and wanted to test-out:

- Added full automation capabilities to PowerValidatedSolutions, including:

    Invoke-PasswordPolicyManager – a dedicated cmdlet to generate an HTML report showing the existing configuration across the platform without configuration drift

I've gone through the installation [link](https://www.powershellgallery.com/packages/PowerValidatedSolutions/2.0.0.1010)
`Install-Module -Name PowerValidatedSolutions` 
Then from there the link here [Project Site] to install the supporting module
`Set-PSRepository -Name PSGallery -InstallationPolicy Trusted`
`Install-Module -Name VMware.PowerCLI -MinimumVersion 12.7.0`
`Install-Module -Name VMware.vSphere.SsoAdmin -MinimumVersion 1.3.8`
`Install-Module -Name ImportExcel -MinimumVersion 7.1.1`
`Install-Module -Name PowerVCF -MinimumVersion 2.2.0`
`Install-Module -Name PowerValidatedSolutions -MinimumVersion 2.0.0`
i got the syntaxe from the -Examples and choose the Example 1
`Get-Help -Name Invoke-PasswordPolicyManager -Examples`

At that point i got a bunch of time a function missing
`Convert-CssClass`
After a quick search i found this function is in Reporting module,
thus my suggestion to add it in the Readme.

### Suggestion

https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation#installing-the-module
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-Module -Name VMware.PowerCLI -MinimumVersion 12.7.0
Install-Module -Name VMware.vSphere.SsoAdmin -MinimumVersion 1.3.8
Install-Module -Name ImportExcel -MinimumVersion 7.1.1
Install-Module -Name PowerVCF -MinimumVersion 2.2.0
Install-Module -Name PowerValidatedSolutions -MinimumVersion 2.0.0
Install-Module -Name VMware.CloudFoundation.Reporting -MinimumVersion 1.0.6.1004

### PR DESCRIPTION
**Pull request by GaryJBlake**
In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CONTRIBUTING.md) for making a pull request.

**Summary of Pull Request**

- Added `Convert-CssClassStyle` cmdlet to modify the CSS Style in the HTML output.
- Fixed `Publish-*` cmdlets to use `Convert-CssClassStyle` rather than `Convert-CssClass` which is part of VMware Cloud Foundation reporting module.

Signed-off-by: Gary Blake <gblake@vmware.com>

**Type of Pull Request**

- [x] This is a bug fix.
- [ ] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.

**Related to Existing Issues**

Issue Number: Closes #202 

**Test and Documentation Coverage**

- [x] Tests have been completed (for bug fixes / features).
- [ ] Documentation has been added / updated (for bug fixes / features).

**Breaking Changes?**

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Review by tenthirtyam — APPROVED** [review]
LGTM! 🚀

**Comment by abbedsedk** [comment]
Thanks

I just downloaded the zip and imported the .psm1 file module and found there is an occurrence left of the Convert-CssClass
when using the same command "Invoke-PasswordPolicyManager".

`[02-18-2023_09:55:04]   Error at Script Line 15788`
 `[02-18-2023_09:55:04]   Relevant Command: $allSddcManagerPasswordExpirationObject = Convert-CssClass -htmldata $allSddcManagerPasswordExpirationObject`
 `[02-18-2023_09:55:04]   Error Message: The term 'Convert-CssClass' is not recognized as a name of a cmdlet, function, script file, or executable program.`
`Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

**Comment by GaryJBlake** [comment]
Thanks @abbedsedk will double check that and fix it this week.

**Comment by GaryJBlake** [comment]
@abbedsedk applied update to Publish-SddcManagerPasswordExpiration

**Pull request merged**
