### PR TITLE
fix: update `Get-GlobalPermissions` html parsing

### PR DESCRIPTION
**Pull request by bhumitra**
In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CONTRIBUTING.md) for making a pull request.

**Summary of Pull Request**

An issue was found with Get-GlobalPermissions where the response of the API didnt have ParsedHTML data. A code change is needed to read the html from response.content directly. 

```
PS C:\Users\Administrator>         $table = $response.ParsedHtml.body.getElementsByTagName("table")[3]
You cannot call a method on a null-valued expression.
At line:1 char:9
+         $table = $response.ParsedHtml.body.getElementsByTagName("tabl ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

PS C:\Users\Administrator> $response


StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html>  <head>    <title>      Managed Object Browser    </title><style type="text/css"><!--body {  font-family: Verdana, Arial, Helvetic...
RawContent        : HTTP/1.1 200 OK
                    x-envoy-upstream-service-time: 2
                    transfer-encoding: chunked
                    Content-Type: text/html;charset=utf-8
                    Date: Mon, 17 Apr 2023 23:04:19 GMT
                    Server: envoy

                    <!DOCTYPE html PUBLIC "-//W3...
Forms             :
Headers           : {[x-envoy-upstream-service-time, 2], [transfer-encoding, chunked], [Content-Type, text/html;charset=utf-8], [Date, Mon, 17 Apr 2023 23:04:19 GMT]...}
Images            : {}
InputFields       : {}
Links             : {@{outerHTML=<a href="javascript:invokeMethod()">Invoke Method</a>; tagName=A; href=javascript:invokeMethod()}}
ParsedHtml        :
RawContentLength  : 49600



PS C:\Users\Administrator> $response.ParsedHTML.body
```

**Type of Pull Request**

- [x] This is a bug fix.
- [ ] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.
      Please describe:

**Context of the Pull Request***

**Related to Existing Issues**

Issue Number: N/A

**Test and Documentation Coverage**

- [x] Tests have been completed (for bug fixes / features).
- [ ] Documentation has been added / updated (for bug fixes / features).

**Breaking Changes?**

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

After making the fix. 
Screen Shot 2023-04-20 at 11 51 59 AM

### CODE REVIEW

**Comment by tenthirtyam** [comment]
@GaryJBlake - do you want to pull this in for 2.2.0?

**Comment by GaryJBlake** [comment]
@tenthirtyam Yes we should include  this fix with next weeks release

**Comment by tenthirtyam** [comment]
I've updated the `CHANGELOG.md` and module build in https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/241/commits/276b1d04ea42790ba0b2dd841ab72eb967666dc6.

**Review by tenthirtyam — APPROVED** [review]
LGTM!

**Pull request merged**
